### ISSUE TITLE
Minor issue with the transparent search bar

### ISSUE THREAD

**Issue by CallMeIracso** [thomaswang/minimal-twitter#105]
So, it's not a big deal but when you set the search bar to transparent and make the font bigger, the text gets cut off a bit. It's still perfectly usable once you click on it.
![Twitter at 150% font scale](https://user-images.githubusercontent.com/100056482/173448161-60793a99-238f-4892-8613-3ee3b1482745.png)
![Twitter at 200% font scale](https://user-images.githubusercontent.com/100056482/173448165-19b8b357-95cc-43f8-8c25-c1cfebad6856.png)
![Twitter at normal font scale](https://user-images.githubusercontent.com/100056482/173448166-73915f43-54f5-4ab9-b06a-1cd817562633.png)

**Comment by thomaswang** [comment]
Fixed in https://github.com/thomaswang/minimal-twitter/commit/97f87092e468695613da31c4db6ece9aba9dad06, will release in 4.3.0
