### ISSUE TITLE
Zen mode broken?

### ISSUE THREAD

**Issue by rivke41levp656** [thomaswang/minimal-twitter#113]
In the last few days zen mode stopped working for me. If zen mode is enabled it hides everything - the page is just black and blank. With zen mode disabled all seems normal. Tested in both brave and firefox same behavior.

**Comment by thomaswang** [comment]
Fixed in https://github.com/thomaswang/minimal-twitter/commit/766dae93914ab48b015c6923522a9346f9c05f04, will be live in 4.3.0
