### ISSUE TITLE
"Back" button not clickable if feed width is increased and page is zoomed in

### ISSUE THREAD

**Issue by markerikson** [thomaswang/minimal-twitter#12]
Loving the extension so far, but I'm seeing a problem with the "Back" button when there's some page zooming applied:

- Increase page zoom to 120% 
- Set feed width to 600px, save options, reload Twitter
- Click a tweet
- Mouse over the Back arrow button.  Verify that it shows the hover highlight, and clicking it returns to the feed
- Set feed width to 800px, save options, reload Twitter
- Click a tweet
- Mouse over the Back arrow button.  Note that it does _not_ show the hover highlight, and clicking it does nothing.
- Repeat with a width of 700px.  Note that the button may highlight if you are mousing over its right edge, or possibly just to the right of it.

Currently on Firefox 68, Windows 10, and the "Zoom Page WE" extension:

https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we

This may be somewhat over-specific due to the zooming aspect and the extension, but FYI.

**Comment by thomaswangio** [comment]
I'm noticing this on Chrome too

**Comment by thomaswang** [comment]
Seems to be resolved
