### ISSUE TITLE
Disable notification counter and favicon changes

### ISSUE THREAD

**Issue by zyumbik** [thomaswang/minimal-twitter#18]
Hey! Apparently Twitter wants even more attention now and it changes favicon and adds notification counter to the tab title. It would be very nice if there was an option to disable these distracting things entirely or just the favicon change at least.

![image](https://user-images.githubusercontent.com/16729927/63630944-cfb02400-c663-11e9-8c0e-a44a057f4010.png)

**Comment by thomaswang** [comment]
Done, coming soon! Commit: https://github.com/thomaswang/minimal-twitter/commit/5a4fda7e88512db6009bed05c66d240d945fd904
