### ISSUE TITLE
Use escape key to go back

### ISSUE THREAD

**Issue by Pandawan** [thomaswang/minimal-twitter#19]
Hey,

When clicking on a Tweet, it opens a view for that tweet. It'd be nice if pressing the Escape key could back out of that view (as if you were clicking on the back arrow).

Reddit's (relatively) new interface does this when opening a post, and I think it's such a small thing but it makes the experience much better.

EDIT: I know this isn't a visual change like the original intention of this extension, but I think having to create an entirely new extension for this feature seems like overdoing it.

Thanks!

**Comment by thomaswangio** [comment]
Hey @PandawanFr, what OS are you using? I can press `esc` on mac and it already does this.

You can actually press `n` to do a new tweet as well. Here are a list of all the Twitter shortcuts: https://help.twitter.com/en/using-twitter/how-to-tweet#keyboard-shortcuts

**Comment by PandawanFr** [comment]
Hey, this happens on macOS (10.14.6). I tried with both Safari and Edge (Chromium), neither of them work. (I've also tried on a different mac, it didn't work either).

Is that an issue on Twitter's end then?

**Comment by thomaswangio** [comment]
@PandawanFr  i'm on 10.14.6 as well, so that's not the issue. I tried it on Safari and it works fine. Maybe your `esc` key has some issues? Try changing your modifier keys on your mac to a different key and see if it works? https://support.apple.com/en-us/HT207358

**Comment by PandawanFr** [comment]
Just tried it on my Desktop PC (Windows 10) with Edge (Chromium), Edge (non-chromium) and Firefox Developer Edition and get the same issue. So this is definitely not an issue with my mac or keyboard.

The only possible causes for this that I can think of are:
1. We aren't trying the same procedure/we're not talking about the same thing. ([Just to be clear, I'm talking about this action](https://gyazo.com/3e2c7eaf78a6be9a71786df9b21bff23); using `esc` to exit out of the Compose Tweet page works fine).
2. There might have been some changes in their code and you still have the cached version (I tried clearing my cache and reloading). 
3. Some sort of AB testing from Twitter?

If not these three, then I have no idea why this is happening.

**Comment by thomaswangio** [comment]
@PandawanFr oh i'm sorry! thanks for clarifying, I was thinking about "Compose Tweet."

Ok, this feature is definitely do-able!

**Comment by thomaswang** [comment]
This has potential side effects so not going to add this for now, sorry!
