### ISSUE TITLE
No  borders mode

### ISSUE THREAD

**Issue by bnb** [thomaswang/minimal-twitter#2]
Currently there are still some borders in the app that feel a bit out of place. Here's a list of all the ones I can find:

Notifications page:

![image](https://user-images.githubusercontent.com/502396/61682711-9765a080-acc7-11e9-8a6b-7c995cf3f1c0.png)

Liked page:
![image](https://user-images.githubusercontent.com/502396/61682705-8d43a200-acc7-11e9-9e5b-9b1b37108f6f.png)

Latest tweets/home:
![image](https://user-images.githubusercontent.com/502396/61682720-a3516280-acc7-11e9-979b-bab4e6e16b72.png)

Search:
![image](https://user-images.githubusercontent.com/502396/61682753-c3812180-acc7-11e9-872e-87867f15281b.png)

Profile:
![image](https://user-images.githubusercontent.com/502396/61682761-ce3bb680-acc7-11e9-9d0c-2e9abac42f59.png)

Looking at inspector, it looks like most of these are coming from the same React Native Web CSS class: 

![image](https://user-images.githubusercontent.com/502396/61682805-ef040c00-acc7-11e9-8ae2-ddb45af911a8.png)

![image](https://user-images.githubusercontent.com/502396/61682835-0fcc6180-acc8-11e9-9098-d05d985d1cf0.png)

![image](https://user-images.githubusercontent.com/502396/61682862-283c7c00-acc8-11e9-95a8-87cba9b97525.png)

I assume this class changes with every build, so I'm not really sure what a solution would be otherwise I'd PR it myself.

In addition to the 1px solid gray (?) bars, there are a few bigger bars like this:

Liked page:
![image](https://user-images.githubusercontent.com/502396/61682705-8d43a200-acc7-11e9-9e5b-9b1b37108f6f.png)

Here's their source, which also seems to be consistently coming from the same css:

![image](https://user-images.githubusercontent.com/502396/61682935-7a7d9d00-acc8-11e9-810c-37f9beec2530.png)

![image](https://user-images.githubusercontent.com/502396/61682937-7c476080-acc8-11e9-95a7-b78ae56a175e.png)

Removing these would be stellar as well ❤️

**Comment by bnb** [comment]
FWIW, I'd be happy to work on this if someone could point me in the right direction about how to dynamically address this CSS. Additionally, it could be nice to see this as a toggle for people who like it as it is vs. people who want no separating borders 👍

**Comment by bnb** [comment]
Also, here is an example of what it looks like with these borders zeroed out on the homepage: 

![image](https://user-images.githubusercontent.com/502396/61683139-49ea3300-acc9-11e9-8ab7-a04f3de481fe.png)

**Comment by thomaswangio** [comment]
I tackled the main borders in the latest Chrome update @bnb!

https://github.com/thomaswangio/minimal-twitter#chrome-customization
