### ISSUE TITLE
remove likes count even after when an user likes

### ISSUE THREAD

**Issue by karanganesan** [thomaswang/minimal-twitter#22]
currently after liking a tweet the number shows up

<img width="677" alt="Screenshot 2019-11-15 at 5 24 11 PM" src="https://user-images.githubusercontent.com/6049925/68941783-ccdd4f00-07cc-11ea-8609-9158054a9521.png">

it would be great to remove that 

<img width="677" alt="Screenshot 2019-11-15 at 5 24 14 PM" src="https://user-images.githubusercontent.com/6049925/68941787-d070d600-07cc-11ea-993c-09b7dd9f7ad3.png">

**Comment by karanganesan** [comment]
also may be the replies count can also be removed

**Comment by thomaswang** [comment]
Done in 4.0! https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8
