### ISSUE TITLE
Request for feature: Super Minimal Mode

### ISSUE THREAD

**Issue by karanganesan** [thomaswang/minimal-twitter#23]
<img width="685" alt="Screenshot 2019-11-15 at 5 26 35 PM" src="https://user-images.githubusercontent.com/6049925/68941919-29406e80-07cd-11ea-91ca-95d70f667781.png">

something like this

we humans always have the tendency either like, see comments, etc

it would be great to use Twitter super minimal just for reading

**Comment by thomaswang** [comment]
No plans to do this, but 4.0 lets you remove all vanity counts! https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8
