### ISSUE TITLE
Navigation bar text

### ISSUE THREAD

**Issue by TomJTaylor67** [thomaswang/minimal-twitter#25]
I only want to have the icons on the side of my screen, I don't want the text e.g "Notifcation, Messages"

**Comment by BubiBalboa** [comment]
This would be great! I'd like the option to hide the text completely, too Right now the hover zone is super big as well so the text shows up all the time unintentionally.  So, thumbs up for this suggestion from me.

**Comment by thomaswang** [comment]
Released in: Released in: https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8
