### ISSUE TITLE
Bug: Account switcher is opened in the wrong position

### ISSUE THREAD

**Issue by shroudedcode** [thomaswang/minimal-twitter#26]
Clicking the account switcher button in the bottom right corner currently results in the account switcher being opened in the wrong position. I haven't changed any of the extension's settings, so this probably affects most users.

The position of the little arrow at the bottom of the popover also doesn't make a lot of sense if the name and username are only shown while hovering over the button, so it should be either moved to the left or the button text should not be hidden while the popover is shown.

![](https://user-images.githubusercontent.com/29176678/80101716-15661900-8572-11ea-904b-3393deff2c99.gif)

Thanks for making this great extension by the way, it really improves the Twitter user experience a lot!

**Comment by thomaswang** [comment]
Hey, @shroudedcode thanks for reporting this! I fixed this and a couple of other small things in https://github.com/thomaswang/minimal-twitter/releases/tag/2.30. 

It's available now in Firefox and pending review in the Chrome Web Store.

<img width="772" alt="Screen Shot 2020-04-23 at 1 42 27 PM" src="https://user-images.githubusercontent.com/41944255/80148081-586fbe80-8569-11ea-8ed7-b53853febb81.png">

**Comment by shroudedcode** [comment]
Thanks a lot for the quick fix, @thomaswang!
