### ISSUE TITLE
Feature Request: Ability to mark your place and auto-scroll to it

### ISSUE THREAD

**Issue by GuanoLad** [thomaswang/minimal-twitter#27]
Because of my time zone, hundreds of tweets happen overnight and it's hard to keep track when the feed auto-fills and pushes it down as I try to read it. If I had a way to mark my place with a colour change, and another button to take me there, I could avoid missing anything that happens. I base this idea on a script for Old Twitter by ArmEagle called Twitter Last Read.

**Comment by thomaswang** [comment]
No plans to do this for now, sorry!
