### ISSUE TITLE
Search Box Missing

### ISSUE THREAD

**Issue by eborenst** [thomaswang/minimal-twitter#28]
I keep my browser at 1280px wide (half of a 1440p monitor). If I turn off the add-on, the search box is visible at this size, but it appears to be off-screen when using the add-on. If I make the window somewhat bigger, the search box appears. Same behavior at all feed width sizes.

This seems like a bug?

**Comment by thomaswang** [comment]
@eborenst thanks for catching this. I removed the buggy media query, not sure why it was there originally, but this version should work: https://github.com/thomaswang/minimal-twitter/releases/tag/2.40.

Currently pending review on Chrome/Firefox.

**Comment by eborenst** [comment]
I'm actually still having this issue on version 2.5/June 27.

**Comment by thomaswang** [comment]
@eborenst The behavior that is currently that is intended, the search box disappears when the tweet button shrinks to a circle. At those window sizes, you can go to the "explore tab" to search. I'll look into a better solution in a future release 😀

**Comment by eborenst** [comment]
Ok, got it. I failed to notice that there's a search box on the Explore tab, but that works. Thanks!
