### ISSUE TITLE
Feature Request: Background Colour Customization

### ISSUE THREAD

**Issue by Firedingo** [thomaswang/minimal-twitter#29]
One of the things that annoys me and makes looking at the site harder is the flat colour of the background and the tweets. The ability to set a different colour in the background to add contrast would be good.

Otherwise I will say I love the add-on as it is and it's a total lifesaver for me <3

**Comment by thomaswang** [comment]
Thanks for the issue @Firedingo! Definitely would be a good customization, I'll look into it when I have some time.

**Comment by thomaswang** [comment]
No plans to do this for now, but this can potentially be done with userstyles (https://userstyles.org/) or something like Ublock Origin https://github.com/gorhill/uBlock :)
