### ISSUE TITLE
Top align navigation on FireFox doesn't work.

### ISSUE THREAD

**Issue by LWGShane** [thomaswang/minimal-twitter#31]
I'm having a issue on FireFox where if you enable "top align navigation", the navigation is still center-aligned.

**Comment by thomaswang** [comment]
Fixed! You can update on FF :) https://addons.mozilla.org/en-US/firefox/addon/min-twitter/

https://github.com/thomaswang/minimal-twitter/commit/535e04fff56f5d21c35fa4e8855d7a31fef38824
