### ISSUE TITLE
Search Bar Getting Cut Off

### ISSUE THREAD

**Issue by hepatocyte** [thomaswang/minimal-twitter#33]
Hello! I'm loving this extension so far, but noticed that for me the "Search Twitter" bar gets cut off when I click on it. I use Google Chrome, and my laptop screen resolution is 1366 x 768. I use the second smallest text size.

![cut off](https://user-images.githubusercontent.com/68362581/87621822-84b55a00-c6d6-11ea-81ca-cbba92f7cfac.PNG)

**Comment by thomaswang** [comment]
Hey @hepatocyte! Thanks for catching – I added `z-index: 1` to the search bar https://github.com/thomaswang/minimal-twitter/commit/98af43ba4a8583e665351157a2e1f47788014484, not a perfect solution because there's still an overlap but don't want to change too much.
