### ISSUE TITLE
feed aligns to the left if window width is small enough

### ISSUE THREAD

**Issue by eyehol3** [thomaswang/minimal-twitter#37]
it should have been centered instead(?) 
not centered:
![image](https://user-images.githubusercontent.com/49121161/90250265-804e9f00-de44-11ea-883c-e70ded5abb24.png)
i increased the width a bit and it's centered 
![image](https://user-images.githubusercontent.com/49121161/90250314-8b093400-de44-11ea-86de-66adc9bf4436.png)

**Comment by thomaswang** [comment]
I believe this commit https://github.com/thomaswang/minimal-twitter/commit/4e9420ac9074cc0e272d58948f5f460473904257 should fix your issue! I'm actually not quite sure why I had it this way in the first place. I did test it again without this media query and everything works well, thanks for the feedback!
