### ISSUE TITLE
extension pauses videos

### ISSUE THREAD

**Issue by gearan** [thomaswang/minimal-twitter#39]
Love the extension for clearing the clutter but it also keeps pausing videos I want to watch. I like that it removed auto play, but if a scroll even a little the extension pauses the video, sometimes it just pauses it at random even when I am not touching anything. It is extremely annoying. Is there a fix for this?

**Comment by thomaswang** [comment]
Finally caught this bug! 

https://github.com/thomaswang/minimal-twitter/releases/tag/2.70

Update to 2.70 @gearan
