### ISSUE TITLE
Search seems to have disappeared

### ISSUE THREAD

**Issue by Sushubh** [thomaswang/minimal-twitter#41]
I imagine Twitter changed something in their code which broke the `explore` page hiding the search bar?

**Comment by Sushubh** [comment]
Twitter seems to have messed up a bit more today. While writing a tweet, it kept on triggering shortcuts with this addon. I might have unfollowed a few accounts and following some as a result. Had to disable it for the time being. Going back to native twitter.com is so messed up now. Thank you for this product!

**Comment by thomaswang** [comment]
https://github.com/thomaswang/minimal-twitter/issues/40#issuecomment-718732627

**Comment by thomaswang** [comment]
https://github.com/thomaswang/minimal-twitter/issues/40
