### ISSUE TITLE
"show search bar" , "show search filter", "show 6 media thumbnail (under search bar)" option , Preferred width of Twitter feed - 900 pixels, 1000 pixels ,...

### ISSUE THREAD

**Issue by tjngkrfud** [thomaswang/minimal-twitter#44]
Hi! I need "show search bar" , "show search filter", "show 6 media thumbnail (under search bar)" option ,
Preferred width of Twitter feed - 900 pixels, 1000 pixels ,...
plz plz .. thank you so much

**Comment by devmbm** [comment]
I support this as well, either search bar or button, as it has disappeared.
Thanks, the plugin looks great

**Comment by holamarina** [comment]
me too. there is nothing to do when you want to search but to deactivate the extension.

**Comment by thomaswang** [comment]
More width options and search is better in 4.0: https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8

**Comment by devmbm** [comment]
Thanks for the update ✨ I look forward to when it is available on the Firefox add-on library.
