### ISSUE TITLE
Feed not showing after updating to 2.75

### ISSUE THREAD

**Issue by Flumee** [thomaswang/minimal-twitter#47]
Hi! 
Since the recent release, everything is loading exept all the feed.
If we try to load at first only /home, the feed does not appear. On the other hand if we go to /explore /notification or any page via the left menu and we go back to /home, the content is loading and showing.
I'm using ungoogled chromium but I've done some tests on Chrome as well. same issue.
Thanks

**Comment by thomaswang** [comment]
Oh @Flumee you're totally right, sorry fixing now.

**Comment by thomaswang** [comment]
Ok should be fixed now, update to 2.76. Thank you @Flumee for the heads up! 

Feel re-open this or open a new issue if you see this again.
