### ISSUE TITLE
Hide notifications counter while still displaying the button

### ISSUE THREAD

**Issue by chriskorosu** [thomaswang/minimal-twitter#49]
I would love to be able to hide the notification counter (i.e. the blue number displaying the number of unread notifications) while still keeping the notification icon on screen. 

![image](https://user-images.githubusercontent.com/47898552/111517296-4a9bcc80-872b-11eb-8fb6-023007a35935.png)

Use Case: I want to be able tweet out things without getting distracted in the mornings during work sessions. But seeing the notifications makes me wonder who they're from, etc. I could disable the button altogether, as that's currently an option. But I still want the button to be on screen in case I want to go through the notifications at a later time (usually in the evening).

Thank you for a great extension! ♥

**Comment by thomaswang** [comment]
No plans to do this for now, but this can potentially be done with userstyles (https://userstyles.org/) or something like Ublock Origin https://github.com/gorhill/uBlock :)
