### ISSUE TITLE
Lower right Tweet button/drawer settings no longer working.

### ISSUE THREAD

**Issue by githubsterer** [thomaswang/minimal-twitter#50]
Maybe it's just me but something happened today where I cannot hide the lower right Tweet button, even when that setting is on. I've reloaded the extension and toggled the setting but the button will not disappear as it has always done before. Also, the lower right drawer setting to show/hide is not working as well.

**Comment by thomaswang** [comment]
Yes, this is a recent change by Twitter. Will address this when I have time, otherwise PR help would be appreciated :)

**Comment by thomaswang** [comment]
https://github.com/thomaswang/minimal-twitter/pull/53

**Comment by D3SOX** [comment]
Still not working for me. Maybe Twitter changed something again

![image](https://user-images.githubusercontent.com/24937357/119647115-2ee62e00-be20-11eb-8cbb-fe03973af223.png)
![image](https://user-images.githubusercontent.com/24937357/119647136-33aae200-be20-11eb-89f6-d349c4318f3b.png)

**Comment by thomaswang** [comment]
@D3SOX should be fixed now! https://github.com/thomaswang/minimal-twitter/commit/04912e1c0750e10d075f745a3168f84db8b572b8

**Comment by D3SOX** [comment]
I can confirm that it works with the new version. Thank you!
