### ISSUE TITLE
Option to completely hide muted tweets

### ISSUE THREAD

**Issue by sspreng** [thomaswang/minimal-twitter#51]
Currently, when a term is muted on Twitter, the muted tweet is still displayed in the replies. It would be nice to have the option to completely hide these muted tweets from view for an even more minimal experience. Just a suggestion :)

Thanks for making this extension, btw. I've been using it for years!

![muted_tweet](https://user-images.githubusercontent.com/80741149/116369023-c757a700-a7bd-11eb-87ba-bbb9e01874d9.png)

**Comment by thomaswang** [comment]
No plans to do this for now, but this can potentially be done with userstyles (https://userstyles.org/) or something like Ublock Origin https://github.com/gorhill/uBlock :)
