### ISSUE TITLE
Search Bar Glitch

### ISSUE THREAD

**Issue by fapires** [thomaswang/minimal-twitter#52]
Recently the search bar started to show this strange glitch showing the user name
<img width="243" alt="CleanShot 2021-05-13 at 09 57 57@2x" src="https://user-images.githubusercontent.com/8724228/118128759-b750e180-b3d1-11eb-8d76-2bea50e0f5c3.png">

**Comment by thomaswang** [comment]
I believe this should be fixed! https://github.com/thomaswang/minimal-twitter/releases/tag/2.80
