### ISSUE TITLE
Add option to remove comments count.

### ISSUE THREAD

**Issue by Leuug** [thomaswang/minimal-twitter#55]
Currently twetts are shown this way:
![image](https://user-images.githubusercontent.com/58122451/120379949-e4205680-c2f6-11eb-9080-c482fe1fa1fb.png)

Would be great to be able to hide the comments count like this:
![image](https://user-images.githubusercontent.com/58122451/120380379-79234f80-c2f7-11eb-99f5-9ac1351ee25f.png)

**Comment by thomaswang** [comment]
https://github.com/thomaswang/minimal-twitter/pull/59
