### ISSUE TITLE
Search bar does not show up on my 1280 px display

### ISSUE THREAD

**Issue by zaouch** [thomaswang/minimal-twitter#56]
Search bar does not show up on my 1280 by 1024 display.
![Screenshot from 2021-06-05 13-59-57](https://user-images.githubusercontent.com/31248577/120901776-54e3ad80-c62c-11eb-8cbb-d3bac6a50735.png)

**Comment by thomaswang** [comment]
Fixed in 4.0: https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8
