### ISSUE TITLE
There is no "Search" 

### ISSUE THREAD

**Issue by Gsisneros1** [thomaswang/minimal-twitter#61]
100% LOVE the extension. Unfortunately, the search bar is not showing up. Any ideas?

![Screen Shot 2021-09-04 at 8 58 16 AM](https://user-images.githubusercontent.com/90102329/132098873-f66642c0-1604-4d19-b452-ff0634cb4729.png)

![Screen Shot 2021-09-04 at 9 00 04 AM](https://user-images.githubusercontent.com/90102329/132098929-9b32d2e2-fd77-4119-9918-a6a5b0c89a37.png)

**Comment by mactkg** [comment]
I use https://twitter.com/explore (`#` icon at sidebar) to search.
