### ISSUE TITLE
Remove messages button

### ISSUE THREAD

**Issue by srid** [thomaswang/minimal-twitter#62]
Would be great to be able to remove the 'Messages' thingy in the sidebar. Just like the 'Remove notifications button'. 

[Some of us](https://twitter.com/dhh) use none of the replies, notifications or messages feature.

**Comment by srid** [comment]
Looks like a fairly simple change. Just need to hide the element with ID `AppTabBar_DirectMessage_Link`, duplicating the code for notifications button as its base:

https://github.com/ThomasWang/minimal-twitter/blob/2f95680dcbf82310f3878925beae0673ded1966d/chrome/applyOptions.js#L153-L157

**Comment by thomaswang** [comment]
https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8

**Comment by srid** [comment]
Thanks! Fantastic extension. Love the "Hide vanity count" setting.
