### ISSUE TITLE
Would be nice if there was an option to remove "More Tweets"

### ISSUE THREAD

**Issue by ricardosaracino** [thomaswang/minimal-twitter#63]
![image](https://user-images.githubusercontent.com/759253/136712840-a27916a3-df32-4985-ba2b-a45ee20d1ea7.png)

**Comment by thomaswang** [comment]
Closing for now, no good selectors for removing these

**Comment by slorber** [comment]
Can confirm 🤪 this is becoming so annoying

https://twitter.com/sebastienlorber/status/1490704646230482949

**Comment by ricardosaracino** [comment]
> Can confirm 🤪 this is becoming so annoying
> 
> https://twitter.com/sebastienlorber/status/1490704646230482949

well that is something 🤕

**Comment by thomaswang** [comment]
> ```css
> h2 > div:has(> span:contains("More Tweets")) {
>   padding-top: 100rem !important;
> }
> ```

FYI - https://stackoverflow.com/a/4561376/7948880
