### ISSUE TITLE
Add option to hide tweets order navbar

### ISSUE THREAD

**Issue by HugoGEORGET** [thomaswang/minimal-twitter#65]
Twitter has added the tweets ordering option as a navbar at the top of the main page.

![twitter-tweets-order-navbar](https://user-images.githubusercontent.com/9433512/143762796-1158219d-fabd-4fc6-8f1c-0794182639b4.png)
(Sorry for the french screecap)

For minimalism purposes, it could be hidden.
The selector is `div[data-testid="primaryColumn"] nav[role="navigation"]`on Firefox. I don't know if Chrome's the same or not.

**Comment by thomaswang** [comment]
Not seeing this UI? Feel free to re-open if it's still an issue.
