### ISSUE TITLE
Breaks Spaces

### ISSUE THREAD

**Issue by richardpickett** [thomaswang/minimal-twitter#68]
Minimal-twitter slides the spaces elements up almost out of site in the top right.

**Comment by thomaswang** [comment]
@richardpickett thanks for flagging this, can you help by posting a screenshot? I haven't seen spaces elements on web myself, and after doing some searching I'm still not sure what you might be referring to. I looked at [this Spaces on web tweet announcement](https://twitter.com/TwitterSpaces/status/1397688581846568961), but this UI seems to work fine with the extension.

![twitter com_TwitterSpaces_status_1397688581846568961](https://user-images.githubusercontent.com/41944255/146863138-7c45c3f3-db09-43eb-bb9c-b5e5c3064d22.png)
