### ISSUE TITLE
Firefox: Hidden Navigation Labels Only Works in English

### ISSUE THREAD

**Issue by beachsam0rai** [thomaswang/minimal-twitter#7]
Hola, 

Hidden navigation labels only works in English (Firefox 68.0.1). I tried Turkish and Swedish but they're like this.

![Screenshot_2019-07-25 En Son Tweetler Twitter](https://user-images.githubusercontent.com/53288193/61847104-1c141280-aeb2-11e9-9e5d-09b92ec3eeb6.png)

**Comment by thomaswangio** [comment]
Latest release partially addresses this issue!

Search is a a bit harder to target, didn't want to mess with it too much: https://github.com/thomaswangio/minimal-twitter/releases/tag/2.7

**Comment by beachsam0rai** [comment]
Confirmed!

**Comment by beachsam0rai** [comment]
Similar to this issue, new ''preferences'' features only works in English.

**Comment by thomaswang** [comment]
4.0 has options to address this! https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8
