### ISSUE TITLE
misaligned profile picture relative to non-extension view

### ISSUE THREAD

**Issue by h3oCharles** [thomaswang/minimal-twitter#70]
ava - avatar / profile picture
bg - background

when trying to make an ava+bg combo design (so bg texture would perfectly flow to ava), I encountered an issue where switching back and forth between extension enabled and disabled makes the avatar not perfectly align with a template I made

here's a template I made by taking a screenshot of the site at 100% zoom using the extension and 700px width at 1080p (all of these should be 1500x500, if not, please let me know) and using Inkscape to overlay the images I use as well as the circle around ava
![twitter bg test crop](https://user-images.githubusercontent.com/8020330/147407831-e2765db6-db2b-44eb-a967-518ad4a03b9c.png)

here's a template I made without using the extension at 100% zoom at 1080p
![twitter bg nothing crop](https://user-images.githubusercontent.com/8020330/147408456-0cb11ebb-759a-49e8-a19c-990a09190171.png)

overlap these two together, and you will notice that the red circle (alignment for ava) is different
![twitter bg stacked](https://user-images.githubusercontent.com/8020330/147408461-033fe861-7f6b-401c-ac1a-0b4acd8b64e2.png)

I also noticed that changing the width in extension options also moved the ava, not sure how to approach that too

is there any possibility this can be fixed? or the scaling prevents from doing this kind of precision?

**Comment by thomaswang** [comment]
Please try testing this in the new 4.0 version (https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8)! Closing this for now but feel free to re-open if it's still an issue.
