### ISSUE TITLE
Hide login prompt for logged out users

### ISSUE THREAD

**Issue by Nooshu** [thomaswang/minimal-twitter#76]
Is it possible to add a feature to hide the login prompt when using Twitter as a logged-out user?

See the image below as an example:
<img width="1238" alt="Screenshot 2022-01-10 at 18 52 23" src="https://user-images.githubusercontent.com/1223960/148822797-bcfe8ca7-269f-4f7d-ac43-9b4e82066251.png">

I thought this would be a nice feature from the [tweet here](https://twitter.com/hankchizljaw/status/1480546889724481537).

**Comment by thomaswang** [comment]
Done! https://github.com/thomaswang/minimal-twitter/blob/cb8002a2c9e5cf22e01ec47390be9f692f51baeb/extension/content/main.css#L13

**Comment by thomaswang** [comment]
Actually had to revert this change – it interferes with other elements. There's no good selector for the banner.
