### ISSUE TITLE
Clicking the extension button doesn't open Twitter in a new tab

### ISSUE THREAD

**Issue by akoskm** [thomaswang/minimal-twitter#77]
As of today, clicking the extension button in the toolbar doesn't open twitter.com in a new browser tab.
Instead, it brings up this menu:

![image](https://user-images.githubusercontent.com/3111627/149087919-ac8a9523-339b-48a4-ae33-4718c4e517b7.png)

**Comment by thomaswang** [comment]
Yep, hit the icon on the top right to open twitter.com

**Comment by akoskm** [comment]
That's right! Now I have to click the extension icon then the icon inside this panel to access Twitter, instead of just clicking it once.
I feel the customization dropdown shouldn't be the default action when you click the icon of the extension.
Instead, it could be somewhere in a right-click menu, like for Notifier for Gmail:

![image](https://user-images.githubusercontent.com/3111627/149276452-addf82c1-57da-47d3-9338-93d1162fb240.png)
