### ISSUE TITLE
Expand your timeline with Topics

### ISSUE THREAD

**Issue by Lyceris-chan** [thomaswang/minimal-twitter#78]
![image](https://user-images.githubusercontent.com/52329982/150094792-26aa65ca-0918-43f7-8f2e-078ef8acf662.png)

first of all thanks for your work on this extension but it seems like twitter added something new to nag people with.

**Comment by thomaswang** [comment]
<img width="433" alt="CleanShot 2022-01-19 at 10 00 29@2x" src="https://user-images.githubusercontent.com/41944255/150156725-fae3e94b-211e-4afc-a0a3-a073b9b3ba1c.png">

Hey! This was recently added (https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L490). Find it in Extras and "Show More"
