### ISSUE TITLE
Lists is not showing in the sidebar even if it's turned on in Customize

### ISSUE THREAD

**Issue by akoskm** [thomaswang/minimal-twitter#87]
https://user-images.githubusercontent.com/3111627/155664162-1b0ed0e6-05a4-46b7-8874-4ceccc65b992.mov

**Comment by thomaswang** [comment]
Hey @akoskm! Not everyone has access to lists. If you have Twitter Blue, it replaces it with Top Articles, and in your case, it looks like Communities?
