### ISSUE TITLE
Add an option to persist the last-selected choice for the Home Feed sort

### ISSUE THREAD

**Issue by chrismessina** [thomaswang/minimal-twitter#96]
According to @CaseyNewton, Twitter's new Latest Tweets design [doesn't respect your previous choice](https://twitter.com/CaseyNewton/status/1502733890988953608).

Could you add an option to select your Home Feed sorting option that is persistent?

**Comment by thomaswang** [comment]
![CleanShot 2022-03-12 at 16 28 52@2x](https://user-images.githubusercontent.com/41944255/158035705-8a97acc5-b8ca-47eb-b482-000104d2032f.png)

I believe "Always Show Latest Tweets" is what you're looking for. Feel free to re-open if that's not the case

**Comment by chrismessina** [comment]
LOL, nice! Hopefully it'll address Casey's needs!
